### ISSUE TITLE
How can I get the  library of HSI denoising algorithms

### ISSUE THREAD

**Issue by coderXuXiang** [Vandermode/QRNN3D#2]
Hello Kaixuan Wei,

  I want to get the library of HSI denoising algorithms you provided in readme.md,but i can‘t find  it from the link you gave, can you tell me where is?

**Comment by Vandermode** [comment]
Hi, the Onedrive link has been updated

**Comment by coderXuXiang** [comment]
> Hi, the Onedrive link has been updated

Thanks a lot!
